### ISSUE TITLE
add tag: `regression`

### ISSUE THREAD

**Issue by refack** [nodejs/CTC#106] opened 2017-04-17 19:17 UTC
I'm suggesting adding a `regression` tag to issues/PRs in `nodejs/node`.
Aside from just differentiating those issues, I think they should get higher priority as well.
This tag should cover `master` breakages i.e. "Regression Tests" failures :-D

**Comment by Fishrock123** [comment] 2017-04-18 15:12
Isn't that pretty much also covered by `confirmed-bug`?

**Comment by refack** [comment] 2017-04-18 18:12
I think `confirmed-bug` are newly discovered bugs, where probably the solution should come with a new regression test-case.
IMHO "Regression"s are worse, because "confirmed-bug"s could have been hidden there forever, while regression mean someone (or CI) discovered that something that used to work stopped working, means that for someone a previously working system became broken.

P.S. From my experience this distinction is commonly used to prioritize issues.

**Comment by refack** [comment] 2017-04-18 18:17
To use an analogy, in most places I worked in/with, a new "confirmed bug" was something you talk about with someone first thing in the morning.
A "regression" means a beeper in the middle of the night.

**Comment by addaleax** [comment] 2017-04-18 18:21
@refack Right, and by that analogy we don’t have a regression label because nobody here has beepers for Node core (I think). :smile: Also, I don’t think there’s much point in explicitly prioritizing beyond `confirmed-bug` – it won’t usually get an issue fixed any sooner.

**Comment by refack** [comment] 2017-04-18 19:09
Obv 😄. 
I know there are no direct clients, but there are frustrated devs, that get red on the CI and don't know why.
I'll watch it. Hope others will as well.
https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3Aregression

**Comment by aqrln** [comment] 2017-04-18 19:16
@refack if a bug troubles someone enough, it will be fixed regardless of it being a new one or a regression. If no one volunteers for it, it may be open indefinitely, again, regardless of the nature of the bug. That's how open source works ¯\\\_(ツ)\_/¯
That said, I'm not gonna argue that this distinction may make sense, especially given that you've already created the label. I think the issue can be closed?

**Comment by bnoordhuis** [comment] 2017-04-18 19:41
Looks useful to me.  I'll close but @refack, you might want to post a PSA on nodejs/node if you want collaborators to start using it - not that many people watch nodejs/CTC.

**Comment by refack** [comment] 2017-04-18 19:41
Yeah I thought about closing. Though the secondary point what to document its significance.
OSS is obviously good-faith volunteering, but IMHO issue priorities help communicate our attentiveness to the users, respect to the devs' time, and guidance to volunteers.

One more point, a new bug can stay orphan, but for resgressions there's an easy solution: reversion.
( @bnoordhuis stole my "close" )

**Closed as completed by bnoordhuis** 2017-04-18 19:41 UTC

**Comment by aqrln** [comment] 2017-04-18 19:52
> One more point, a new bug can stay orphan, but for resgressions there's an easy solution: reversion.

Sounds reasonable.
